### ISSUE TITLE
Archive.org can't display scraped franklin websites

### ISSUE THREAD

**Issue by alexcarol** [adobe/helix-project-boilerplate#174]
### Expected Behaviour
Archive.org shows the website as it was.

### Actual Behaviour
The website appears blank and the console shows: “Uncaught SyntaxError: Unexpected token ‘export’“, for lib-franklin and scripts respectively.

#### Steps to Reproduce
Access either of these URLs
- https://web.archive.org/web/20230201084316/https://www.netcentric.biz/
- https://web.archive.org/web/20230102083751/https://www.theplayers.com/

#### Logs taken while reproducing problem
“Uncaught SyntaxError: Uneexpected token ‘export’“

**Comment by trieloff** [comment]
This seems to be a problem with `archive.org` and should be reported there.
