### ISSUE TITLE
Proper Process for installing and using NPM Packages

### ISSUE THREAD

**Issue by jenter** [adobe/helix-project-boilerplate#175]
Hello, I was curious as to the proper process with adding npm packages and utilizing within the workflow. 
We are scoping out some options with your team, and judging the scalability with enhancing the HTML parsing.

So if you install a package with the typical `npm i *` and then try the standard `import { example } from "example"`, you will get an error. I am assuming the docker container and/or proxy is not seeming to understand the path. 
I will list the details below, but this question is really just around the appropriate steps with how adding / interacting with NPM packages 

### Expected Behaviour

I would like the install a npm package, then import and use it. 

### Actual Behaviour

Console error: 
`failed to load module for footer TypeError: Failed to resolve module specifier "EXAMPLE" ...`

### Reproduce Scenario (including but not limited to)

`npm i html-to-json-parser`
`import { HTMLParser } from "html-to-json-parser"`

console error: 
`failed to load module for footer TypeError: Failed to resolve module specifier "html-to-json-parser". Relative references must start with either "/", "./", or "../".`

**Comment by jenter** [comment]
cc @davidnuescheler @trieloff @tripodsan

**Comment by tripodsan** [comment]
hi @jenter 
- where exactly do you want to use the imported npm package?
- what docker container are you referring to? (we don't use docker)

**Comment by jenter** [comment]
> hi @jenter
> 
> * where exactly do you want to use the imported npm package?
> * what docker container are you referring to? (we don't use docker)

@tripodsan - hey, thanks for the quick response. 
`where exactly do you want to use the imported npm package?`
Currently we were just testing with a new test JS file in `blocks/` while reviewing

`what docker container are you referring to?`
This might have been created by the "helix-bot" or "@adobe/helix-cli" when the repo was cloned and initialized. 
![image](https://user-images.githubusercontent.com/1368216/217028651-0ce1df81-3a61-4eac-9ae3-540c1d2fafc0.png)

**Comment by rofe** [comment]
Agreed. The default development experience for Franklin is using local developemt as described in the [README](https://github.com/adobe/helix-project-boilerplate#readme). The configuration in question has been removed from the `main` branch in the meantime, and we are looking for a better way to surface experimental features in the future. Sorry for any inconveniences this may have caused.

cc @tripodsan @trieloff @davidnuescheler

**Comment by jenter** [comment]
> > Currently we were just testing with a new test JS file in blocks/ while reviewing
> 
> well, using 3rd party libraries in helix client-side is supported out-of-the box with the boilerplate project. if you need this, you either:
> 
> * grab the minified release of that lib and put it somewhere in the repo, eg in `/scripts/thirdparty`
> * or use a bundler and deploy the bundles....but this is usually overkill
> 
> > This might have been created by the...
> 
> forget about this. it is not needed for helix. those are config files when you want to use [github codespaces](https://github.com/features/codespaces) for development, instead of using your local console.
> 
> @trieloff @rofe @davidnuescheler we should remove those, otherwise people get confused.

Thanks @tripodsan makes sense, ok. I will proceed with a webpack bundle then while testing, but just wanted to confirm I wasn't missing anything with best practices.. so thanks for the notes. 

I appreciate the rapid response from yourself and @rofe - was helpful in communicating with my team.

**Comment by trieloff** [comment]
@jenter did you develop this in GitHub Codespaces?

**Comment by jenter** [comment]
> @jenter did you develop this in GitHub Codespaces?

@trieloff -- not yet, 
this is just local currently, in testing options with importing npm parsers and [rollupjs](https://rollupjs.org/)

**Comment by trieloff** [comment]
Got it. We generally discourage the use of bundlers like `rollup` because they make the development process less transparent, encourage reckless use of dependencies, and offer little advantage in terms of performance (on Franklin, that is – which has code splitting and deferred module loading tightly tuned to the HTTP/2 delivery of the integrated CDN)

**Comment by jenter** [comment]
> Got it. We generally discourage the use of bundlers like `rollup` because they make the development process less transparent, encourage reckless use of dependencies, and offer little advantage in terms of performance (on Franklin, that is – which has code splitting and deferred module loading tightly tuned to the HTTP/2 delivery of the integrated CDN)

@trieloff makes sense, we will use rollup temporarily, but I will reach out for best practices on this + other things once we have our flow determined. Some of this is just testing, so when we have a clear plan.. then I will reach out with your feedback on how to best integrate things like module dependency + typescript support.  
thanks for your notes

**Comment by trieloff** [comment]
I've asked the team for your email address so I can invite you to our employers' shared slack channel. Happy to jump on a joint debugging session.
