### ISSUE TITLE
Unhandled Promise Rejection in lib-franklin fetchPlaceholders

### ISSUE THREAD

**Issue by karlpauls** [adobe/helix-project-boilerplate#203]
There is a potential for an Unhandled Promise Rejection in the fetchPlaceholders of lib-franklin. The promise is wrapping the fetch call in a try/catch but as there is no await, it should instead add a catch at the end of the chain. Otherwise, a rejected fetch results in an unhandled promise.

Furthermore, the response status of the fetch is not checked which will make it potentially fail on the .json call in case of a request with a response that has a status other than ok. 

Additionally, the resulting json is assumed to have entries with Key and Text in the data section - if that is not the case, the resulting object has undefined keys.

### Expected Behaviour
A rejected fetch should not result in an unhandled promise and a fetch with a status that is not ok should result in a promise rejection. Additionally, the final placeholders object should not contain undefined keys.

### Actual Behaviour
A rejected fetch causes an Unhandled Promise Rejection. A fetch with a status that is not ok errors on the .json call. A result with entries without Key in the data section adds undefined.

### Reproduce Scenario (including but not limited to)
A call to fetchPlaceholders where there is no placeholders sheet. A status code returned other than 200. A mistake in the sheet where no Key is given.

#### Steps to Reproduce
For the main cases (the Unhandled Promise Rejection) it is enough to do a fetchPlaceholders where there is no placeholders sheet set-up.

#### Sample Code that illustrates the problem
```
import { fetchPlaceholders } from '../../scripts/lib-franklin.js';
....
const placeholders = await fetchPlaceholders(`/en`);
```
#### Logs taken while reproducing problem
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (placeholders.json, line 0)
[Error] Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
	promiseEmptyOnRejected
	promiseReactionJob
```

**Comment by tmaret** [comment]
bq. Furthermore, the response status of the fetch is not checked which will make it potentially fail on the .json call in case of a request with a response that has a status other than ok.

+1

Noticed this when investigating Zeiss failing `block-utils.test.js` test. `fetchPlaceholders` did not return without a `200` status when fetching the placeholders.
