### ISSUE TITLE
SVG Icon does not get rendered properly 

### ISSUE THREAD

**Issue by vaibhav2601** [adobe/helix-project-boilerplate#235]
### Expected Behaviour : Specific SVG Icon which is processed through [decorateIcons](https://github.com/adobe/helix-project-boilerplate/blob/main/scripts/lib-franklin.js#L162C23-L162C36) does not get rendered properly.
SVG1 : https://adobe.sharepoint.com/:u:/r/sites/HelixProjects/Shared%20Documents/sites/sunstar/sunstar-engineering/icons/[auto-paint-shop.svg](https://adobe.sharepoint.com/:u:/r/sites/HelixProjects/Shared%20Documents/sites/sunstar/sunstar-engineering/icons/auto-paint-shop.svg?csf=1&web=1&e=lvJ21A)?csf=1&web=1&e=lvJ21A

<img width="165" alt="Screenshot 2023-07-27 at 9 37 02 PM" src="https://github.com/adobe/helix-project-boilerplate/assets/13167708/ab5e5c67-67ce-4f77-b09a-7c2dfe202990">

SVG2 : https://adobe.sharepoint.com/:u:/r/sites/HelixProjects/Shared%20Documents/sites/sunstar/sunstar-engineering/icons/[auto-speciality.svg](https://adobe.sharepoint.com/:u:/r/sites/HelixProjects/Shared%20Documents/sites/sunstar/sunstar-engineering/icons/auto-speciality.svg?csf=1&web=1&e=6rOje0)?csf=1&web=1&e=6rOje0

<img width="156" alt="Screenshot 2023-07-27 at 9 41 18 PM" src="https://github.com/adobe/helix-project-boilerplate/assets/13167708/9d811e39-48e4-4025-99b0-2705dd67c0a2">

### Actual Behaviour
SVG1 over web page :

![image](https://github.com/adobe/helix-project-boilerplate/assets/13167708/e4524d3d-0423-403a-9493-5cd30b4c3900)

SVG2 over web page:

![image](https://github.com/adobe/helix-project-boilerplate/assets/13167708/43ce64fd-b826-4aa7-aa5b-4a8812ce3c65)

Slack Conversation for reference : https://cq-dev.slack.com/archives/C9KD0TT6G/p1690463563902089

**Comment by ramboz** [comment]
When icons use the same `id` property for various groups in their markup, we actually end up having id clashes in Chrome (at least). This would probably both apply to inlined (styled) SVGs and the sprite version, as both end up adding HTML nodes with clashing `id` properties.

One possible approach would be to rewrite all identifiers in the SVGs when we inline them, and prefix with the icon name for instance.
